import { Link, useLocation } from "react-router-dom";
import Icon from "../components/Icon";
export default function PurchaseSuccess() {
  const { state } = useLocation();
  const purchase = state?.purchase || state?.data?.purchase;
  return (
    <div className="success-page">
      <div className="success-icon">
        <Icon name="check" size={32} />
      </div>
      <span className="eyebrow">PURCHASE CONFIRMED</span>
      <h2>Purchase saved successfully</h2>
      <p>Your purchase details have been accepted by the IMS service.</p>
      {purchase && (
        <div className="confirmation">
          <div>
            <span>Transaction ID</span>
            <strong>{purchase.transactionId || "Generated by backend"}</strong>
          </div>
          <div>
            <span>Vendor</span>
            <strong>{purchase.vendorName}</strong>
          </div>
          <div>
            <span>Category</span>
            <strong>
              {purchase.materialCategoryName || purchase.materialCategoryId}
            </strong>
          </div>
          <div>
            <span>Type</span>
            <strong>
              {purchase.materialTypeName || purchase.materialTypeId}
            </strong>
          </div>
          <div>
            <span>Unit</span>
            <strong>{purchase.materialUnitName || purchase.unitId}</strong>
          </div>
          <div>
            <span>Purchase date</span>
            <strong>{purchase.purchaseDate}</strong>
          </div>
        </div>
      )}
      <div className="success-actions">
        <Link className="btn primary" to="/purchase">
          Create another purchase
        </Link>
        <Link className="btn secondary" to="/reports">
          View reports
        </Link>
        <Link className="text-btn" to="/dashboard">
          Go to dashboard
        </Link>
      </div>
    </div>
  );
}
