server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/dbpurchase?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=kani

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Material Service
MaterialServiceConsumer.serviceURL=http://localhost:8088

MaterialCategoryConsumer.serviceURL=http://localhost:8088
MaterialCategoryConsumer.apiURL=/material/controller/getMaterialCategories
MaterialCategoryConsumer.apiURLForById=/material/controller/getMaterialCategoryById/

MaterialTypeConsumer.serviceURL=http://localhost:8088
MaterialTypeConsumer.apiURL=/type/controller/getTypeDetails
MaterialTypeConsumer.apiURLByCategoryId=/type/controller/getTypeDetailsByCategoryId/

# Unit Service
UnitServiceConsumer.serviceURL=http://localhost:8088
UnitServiceConsumer.apiURL=/unit/controller/getUnitDetails
UnitServiceConsumer.apiURLByCategoryId=/unit/controller/getUnitsByCategoryId/

# Vendor Service
VendorServiceConsumer.serviceURL=http://localhost:8087
VendorServiceConsumer.apiURL=/controller/getVendors